# -*- coding: utf-8 -*-
"""Q1_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qS8-5c3lwMfeY1LGlMIEVk-f-5K2bDZC
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from linearRegression.linear_regression import LinearRegression
from sklearn.datasets import make_regression
from metrics import *
import time
import os
from os import path
import seaborn as sns
np.random.seed(45)


N = 5000
P = 30
X = pd.DataFrame(np.random.randn(N, P))
y = pd.Series(np.random.randn(N))
X, y = make_regression(n_samples=5000, n_features=40, n_informative=10, n_targets=1, noise=0.1, random_state=45)
#print(X.shape)
X=pd.DataFrame(X)
y=pd.Series(y)


#Evaluating sklearn's implementation of linear regression
reg = LinearRegression(fit_intercept=True)
st=time.time()
reg.fit_sklearn_LR(X,y)
et=time.time()
y_hat = reg.predict(X)
mae_sklearn, mse_sklearn = mae(y_hat, y),rmse(y_hat, y)
print('For sklearn LinearRegression : \n')
print("time taken:",et-st)
print('RMSE: ', mse_sklearn)
print('MAE: ', mae_sklearn)
print("---------------------------")


#Evaluating solution of linear regression using normal equations
reg = LinearRegression(fit_intercept=True)
st=time.time()
reg.fit_normal_equations(X,y)
et=time.time()
y_hat = reg.predict(X)
mae_svd, mse_svd = mae(y_hat, y),rmse(y_hat, y)
print('For linear regression using normal equations : \n')
print("time taken:",et-st)
print('RMSE: ', mse_svd)
print('MAE: ', mae_svd)
print("---------------------------")



#Evaluating solution of linear regression using SVD
LR = LinearRegression(fit_intercept=True)
st=time.time()
LR.fit_SVD(X,y)
et=time.time()
y_hat = LR.predict(X)
mae_closed_form, mse_closed_form = mae(y_hat, y),rmse(y_hat, y)
print('For linear regression using SVD : \n')
print("time taken:",et-st)
print('RMSE: ', mse_closed_form)
print('MAE: ', mae_closed_form)
print("---------------------------")
